In [3]:
import numpy as np

T = np.array([
    [0.4, 0.5, 0.1],  # H -> H, P, S
    [0.3, 0.4, 0.3],  # P -> H, P, S
    [0.4, 0.4, 0.2]   # S -> H, P, S
])

initial_distribution = np.array([1, 0, 0])

for i in range(0, 5):
    initial_distribution = np.dot(initial_distribution, T)
    print(initial_distribution)



[0.4 0.5 0.1]
[0.35 0.44 0.21]
[0.356 0.435 0.209]
[0.3565 0.4356 0.2079]
[0.35644 0.43565 0.20791]


In [5]:
initial_state_H = np.array([1, 0, 0])
    
#iterate 5 times running the dot product each time.
state_at_t5 = initial_state_H
for i in range(4):
    state_at_t5 = np.dot(state_at_t5, T)

state_at_t5

array([0.3565, 0.4356, 0.2079])

In [10]:
#transition matrix, just the transition probabilities between each site.
T = np.array([
    [0.4, 0.5, 0.1],  # h row
    [0.3, 0.4, 0.3],  # p row
    [0.4, 0.4, 0.2]   # s row
])

# Initial distribution, 1/3 for each site.
initial_distribution = np.array([1/3, 1/3, 1/3])

# first step
initial_distribution = np.dot(initial_distribution, T)

# second step
initial_distribution = np.dot(initial_distribution, T)


initial_distribution

array([0.35666667, 0.43666667, 0.20666667])